services:
  app:
    container_name: front-lec-prod-c
    build:
      context: front/lec-app
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - WDS_SOCKET_PORT=3000
    restart: always
    ports:
      - 80:80
    env_file:
      - .env.production

  municipalities_service:
    build:
      context: back/municipalities_svc
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    restart: always
    environment:
      - PYTHONPATH=/municipalities_svc/src

  buildings_service:
    build:
      context: back/buildings_svc
      dockerfile: Dockerfile.prod
    ports:
      - 5001:5000
    restart: always
    environment:
      - PYTHONPATH=/buildings_svc/src

  geoserver:
    container_name: geoserver-instance
    build:
      context: ./geoserver_data
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./geoserver_data/data/municipalities:/opt/geoserver/data_dir/data/municipalities
      - ./geoserver_data/workspaces/moderate_municipios:/opt/geoserver/data_dir/workspaces/moderate_municipios