services:
  app:
    container_name: front-lec-prod-c
    build:
      context: front/lec-app
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - WDS_SOCKET_PORT=3000
    restart: always
    ports:
      - 80:80
    env_file:
      - .env.development

  municipalities_service:
    build:
      context: back/municipalities_svc
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    restart: always
    environment:
      - PYTHONPATH=/municipalities_svc/src

