services:
  app:
    container_name: lec-app-frontend
    build:
      context: front/lec-app
      args:
        VITE_MUNICIPALITIES_API_URL: /municipalities
        VITE_BUILDINGS_API_URL: /buildings
        VITE_GEOSERVER_API_URL: /geoserver
        VITE_REPORT_API_URL: /report
    image: moderate-lec/lec-app:$DOCKER_IMAGE_TAG
    environment:
      - WDS_SOCKET_PORT=3000
      - MODERATE_GEOSERVER_PROXY_PASS_URL=http://geoserver:8080
      - MODERATE_MUNICIPALITIES_SVC_PROXY_PASS_URL=http://municipalities_service:5000
      - MODERATE_BUILDINGS_SVC_PROXY_PASS_URL=http://buildings_service:5000
      - MODERATE_REPORT_SVC_PROXY_PASS_URL=http://report_service:5000
      
    restart: always
    ports:
      - 80:80

  municipalities_service:
    container_name: municipalities-svc
    build:
      context: back/municipalities_svc
    image: moderate-lec/municipalities-svc:$DOCKER_IMAGE_TAG
    ports:
      - 5000:5000
    restart: always

  buildings_service:
    container_name: buildings-svc
    build:
      context: back/buildings_svc
    image: moderate-lec/buildings-svc:$DOCKER_IMAGE_TAG
    ports:
      - 5001:5000
    restart: always

  report_service:
    container_name: report-svc
    build:
      context: back/report_svc
    image: moderate-lec/report-svc:$DOCKER_IMAGE_TAG
    environment:
      - BUILDINGS_API_URL=$MODERATE_BUILDINGS_SVC_PROXY_PASS_URL
    ports:
      - 5002:5000
    restart: always

  geoserver:
    container_name: geoserver-instance
    image: kartoza/geoserver:2.24.2
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./geoserver_data/data/municipalities:/opt/geoserver/data_dir/data/municipalities
      - ./geoserver_data/workspaces/moderate_municipios:/opt/geoserver/data_dir/workspaces/moderate_municipios

  docx-to-pdf:
    image: moalhaddar/docx-to-pdf:2.1.0-12
    container_name: docx-to-pdf
    ports:
      - "5003:8080"
    environment:
      - pool.size=2
    # volumes:
    #   - ./fonts:/usr/share/fonts/custom
    restart: always
