services:
  app:
    container_name: front-lec-dev-c
    image: moderate-lec/lec-app-dev:$DOCKER_IMAGE_TAG
    build:
      context: front/lec-app
      dockerfile: Dockerfile.dev
    volumes:
      - './front/lec-app:/lec-app'
      - '/lec-app/node_modules'
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
      - VITE_MUNICIPALITIES_API_URL=${MODERATE_MUNICIPALITIES_SVC_PROXY_PASS_URL}
      - VITE_BUILDINGS_API_URL=${MODERATE_BUILDINGS_SVC_PROXY_PASS_URL}
      - VITE_REPORT_API_URL=${MODERATE_REPORT_SVC_PROXY_PASS_URL}
      - VITE_GEOSERVER_API_URL=${MODERATE_GEOSERVER_PROXY_PASS_URL}
    env_file:
      - .env.development

  municipalities_service:
    container_name: municipalities-svc
    image: moderate-lec/municipalities-svc-dev:$DOCKER_IMAGE_TAG
    build:
      context: back/municipalities_svc
      dockerfile: Dockerfile.dev
    volumes:
      - './back/municipalities_svc/src:/municipalities_svc/src'
      - './back/municipalities_svc/data:/municipalities_svc/data'
    ports:
      - ${MUNICIPALITIES_SVC_PORT}:5000
    environment:
      - DEBUG=True
      - PYTHONPATH=/municipalities_svc/src

  buildings_service:
    container_name: buildings-svc
    image: moderate-lec/buildings-svc-dev:$DOCKER_IMAGE_TAG
    build:
      context: back/buildings_svc
      dockerfile: Dockerfile.dev
    volumes:
      - './back/buildings_svc/src:/buildings_svc/src'
      - './back/buildings_svc/data:/buildings_svc/data'
    ports:
      - ${BUILDINGS_SVC_PORT}:5000
    environment:
      - DEBUG=True
      - PYTHONPATH=/buildings_svc/src

  report_service:
    container_name: report-svc
    image: moderate-lec/report-svc-dev:$DOCKER_IMAGE_TAG
    build:
      context: back/report_svc
      dockerfile: Dockerfile.dev
    volumes:
      - './back/report_svc/src:/report_svc/src'
      - './back/report_svc/data:/report_svc/data'
    ports:
      - ${REPORT_SVC_PORT}:5000
    environment:
      - DEBUG=True
      - PYTHONPATH=/buildings_svc/src

  geoserver:
    container_name: geoserver-instance
    image: kartoza/geoserver:2.24.2
    environment:
      - GEOSERVER_ADMIN_USER=user
      - GEOSERVER_ADMIN_PASSWORD=admin
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: always
    volumes:
      - ./geoserver_data/data/municipalities:/opt/geoserver/data_dir/data/municipalities
      - ./geoserver_data/workspaces/moderate_municipios:/opt/geoserver/data_dir/workspaces/moderate_municipios

  docx-to-pdf:
    image: moalhaddar/docx-to-pdf:latest
    container_name: docx-to-pdf
    ports:
      - "5003:8080"
    environment:
      - pool.size=2
    # volumes:
    #   - ./fonts:/usr/share/fonts/custom
    restart: always
