services:
  app:
    container_name: front-lec-dev-c
    build:
      context: front/lec-app
      dockerfile: Dockerfile.dev
    volumes:
      - './front/lec-app:/lec-app'
      - '/lec-app/node_modules'
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
    env_file:
      - .env.development

  municipalities_service:
    container_name: municipalities-svc
    build:
      context: back/municipalities_svc
      dockerfile: Dockerfile.dev
    volumes:
      - './back/municipalities_svc/src:/municipalities_svc/src'
      - './back/municipalities_svc/data:/municipalities_svc/data'
    ports:
      - ${MUNICIPALITIES_SVC_PORT}:5000
    environment:
      - DEBUG=True
      - PYTHONPATH=/municipalities_svc/src

  buildings_service:
    container_name: buildings-svc
    build:
      context: back/buildings_svc
      dockerfile: Dockerfile.dev
    volumes:
      - './back/buildings_svc/src:/buildings_svc/src'
      - './back/buildings_svc/data:/buildings_svc/data'
    ports:
      - ${BUILDINGS_SVC_PORT}:5000
    environment:
      - DEBUG=True
      - PYTHONPATH=/buildings_svc/src

  geoserver:
    container_name: geoserver-instance
    image: kartoza/geoserver:2.24.2
    environment:
      - GEOSERVER_ADMIN_USER=user
      - GEOSERVER_ADMIN_PASSWORD=admin
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: always
    volumes:
      - ./geoserver_data/data/municipalities:/opt/geoserver/data_dir/data/municipalities
      - ./geoserver_data/workspaces/moderate_municipios:/opt/geoserver/data_dir/workspaces/moderate_municipios

