version: "3"

tasks:

  build-dev:
    dotenv: [ '.env.development' ]
    cmds:
    - docker compose -f docker-compose.dev.yaml build # --no-cache

  build-prod:
    dotenv: [ '.env.production' ]
    cmds:
    - docker compose -f docker-compose.prod.yaml build # --no-cache


  start-dev:
    dotenv: [ '.env.development' ]
    cmds:
    # - docker compose -f docker-compose.dev.yaml build --no-cache
      - docker compose -f ${PWD}/docker-compose.dev.yaml up -d --remove-orphans

  start-prod:
    dotenv: [ '.env.production' ]
    cmds:
    # - docker compose -f docker-compose.prod.yaml build --no-cache
    - docker compose -f ${PWD}/docker-compose.prod.yaml up -d --remove-orphans

  logs:
    - docker compose -f ${PWD}/docker-compose.prod.yaml logs -f {{.CLI_ARGS}}

  stop-dev:
    - docker compose -f ${PWD}/docker-compose.dev.yaml down

  stop-prod:
    - docker compose  -f ${PWD}/docker-compose.prod.yaml down
