version: "3"

# Para cargar variables de entono (env-vars)
dotenv: [.env.development]

tasks:

  build-dev:
    - docker compose -f docker-compose.dev.yaml build --no-cache

  build-prod:
    - docker compose -f docker-compose.prod.yaml build --no-cache


  start-dev:
    # - docker compose -f docker-compose.dev.yaml build --no-cache
      - docker compose -f ${PWD}/docker-compose.dev.yaml up -d --remove-orphans

  start-prod:
    # - docker compose -f docker-compose.prod.yaml build --no-cache
    - docker compose -f ${PWD}/docker-compose.prod.yaml up -d --remove-orphans

    
  logs:
    - docker compose -f ${PWD}/docker-compose.prod.yaml logs -f app municipalities_service buildings_service

  stop-dev:
    - docker compose -f ${PWD}/docker-compose.dev.yaml down

  stop-prod:
    - docker compose  -f ${PWD}/docker-compose.prod.yaml down
