FROM python:3.9-slim
WORKDIR /report_svc/src
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src /report_svc/src
COPY data /report_svc/data
ENV FLASK_APP=report_svc:app
CMD ["flask", "run", "--host=0.0.0.0"]

