FROM python:3.9-slim
WORKDIR /municipalities_svc/src
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src /municipalities_svc/src
COPY data /municipalities_svc/data
ENV FLASK_APP=municipalities_svc:app
ENV FLASK_ENV=development
CMD ["flask", "run", "--host=0.0.0.0", "--debug"]

