FROM python:3.9
WORKDIR /buildings_svc/src
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src /buildings_svc/src
COPY data /buildings_svc/data
ENV FLASK_APP=buildings_svc:app
CMD ["flask", "run", "--host=0.0.0.0"]

