FROM node:alpine AS build
WORKDIR /lec-app
COPY package.json .
RUN npm i
COPY . .
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build /lec-app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf