name: Build and push the LEC tool frontend image

on:
  push:
    branches:
      - main

jobs:
  call-build-push-artifact-registry:
    uses: MODERATE-Project/moderate-docs/.github/workflows/reusable-build-push-gar.yml@main
    with:
      project_id: ${{ vars.DEFAULT_GAR_PROJECT_ID }}
      gar_location: ${{ vars.DEFAULT_GAR_LOCATION }}
      gar_repo: ${{ vars.DEFAULT_GAR_REPOSITORY }}
      image_name: tool-lec-frontend
      working_dir: front/lec-app
      build_args: |
        VITE_MUNICIPALITIES_API_URL=/municipalities
        VITE_BUILDINGS_API_URL=/buildings
        VITE_GEOSERVER_API_URL=/geoserver
    secrets:
      wif_provider: ${{ secrets.WIF_PROVIDER }}
      wif_service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
